name: Generate PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Generate_Resume:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
            image: manavendrasen/latex
            options: -v ${{ github.workspace }}:/data manavendrasen/latex Manavendra_Sen_Resume.tex
      - name: Show Files
        run: ls -la
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Resume
          branch: resume
          add_options: 'Manavendra_Sen_Resume.pdf'
          status_options: '--untracked-files'
          skip_dirty_check: true
          push_options: --force
          disable_globbing: true