name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
            image: manavendrasen/latex
            options: -v ${{ github.workspace }}:/data manavendrasen/latex Manavendra_Sen_Resume.tex
      - name: Show Files
        run: ls -la
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Resume
          branch: resume
          file_pattern: '*.pdf'