name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: manavendrasen/latex
      options: --cpus 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker run --rm --volume "`pwd`:/data" manavendrasen/latex main.tex
