name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
            image: manavendrasen/latex
            options: -v ${{ github.workspace }}:/data manavendrasen/latex main.tex
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '.'
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GI_TOKEN }}
          target_url: https://aws-bucket.s3.ap-south-1.amazonaws.com/${{steps.S3.outputs.object_key}}
          state: 'success'
          deployment_id: ${{ steps.test.outputs.deployment_id }}  