name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Display the path
      run: echo $PATH
      shell: bash 
    - name: Generate
      run: ls
      shell: bash
